@hostUrl = http://localhost:5000


### Retornar Estatísticas
GET {{hostUrl}}/v1/trades/statistics/
Accept: application/json

### Simular Compra de BTCUSD
POST {{hostUrl}}/v1/simulations
Content-Type: application/json

{
    "instrument": "btcusd",
    "operation": 1,
    "quantity": 0.004
}

### Simular Venda de BTCUSD
POST {{hostUrl}}/v1/simulations
Content-Type: application/json

{
    "instrument": "btcusd",
    "operation": 2,
    "quantity": 0.002
}

### Simular Compra de ETHUSD
POST {{hostUrl}}/v1/simulations
Content-Type: application/json

{
    "instrument": "ethusd",
    "operation": 1,
    "quantity": 0.004
}

### Simular Venda de ETHUSD
POST {{hostUrl}}/v1/simulations
Content-Type: application/json

{
    "instrument": "ethusd",
    "operation": 2,
    "quantity": 0.004
}